version: '3.1'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/pgsql/data/pgdata
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shatu.jitu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
  pgadmin:
